### ISSUE TITLE
Ajout d'une doc contributeur pour aider à ajout le contenu des derniers numéros ? (CPC 331 332 333)

### ISSUE THREAD

**Issue by Lucas-C** [dboissier/canardpc-base#3]
Bonjour,

Tout d'abord merci pour ce très sympatique projet !
Cette webapp est bien pratique pour retrouver des anciennes notes de CPC :)

Je me rends compte que les numéros de 2016 n'ont pas été ajouté:
serait-il possible d'ajouter un bout de doc dans le README ou le wiki github détaillant comment contribuer du contenu à cette archive ?
Histoire de pouvoir vous envoyer un pull request avec le résumé des tests du dernier numéro.
Comme c'est du Mongo sous le manteau et pas de simples fichiers textes, peut-être qu'un PR n'est pas adapté ceci dit.

Cordialement,

PS: le site référencé dans le footer n'est plus valide: codinjutsu.org

**Comment by dboissier** [comment]
Salut,

Merci pour l'aide proposée. La saisie des numéros est un peu en retard depuis novembre 2105 jusqu'à maintenant.

Les contributeurs ont accès à une interface d'administration rudimentaire. Envoie-moi un MP sur mon compte CPC à travers le post original et je t'ouvrirai un accès.

**Comment by dboissier** [comment]
Pour rappel le lien est : http://forum.canardpc.com/threads/79371-Coincoin-PC-Projet-de-moteur-de-recherche

**Comment by Lucas-C** [comment]
> To be able to send PMs your post count must be 2 or greater.

:(

Tu peux peut-être m'envoyer un PM toi, mon username c'est DrMaxKurt

**Comment by dboissier** [comment]
Done !

**Comment by Lucas-C** [comment]
Merci

**Comment by Lucas-C** [comment]
Bon ben le temps que je me bouge les fesses (un peu moins d'un mois, c'est raisonnable), je vois que tous les derniers numéros ont déjà été mis à jours !

En tout cas un gros BRAVO pour ton boulot : certes tout est toujours perfectible, mais le site est déjà super pratique et complet !

Chapeau ;)
